/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillGapRouteImport } from './routes/skill-gap'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as MarketTrendsRouteImport } from './routes/market-trends'
import { Route as JobMatchingRouteImport } from './routes/job-matching'
import { Route as IndexRouteImport } from './routes/index'

const SkillGapRoute = SkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketTrendsRoute = MarketTrendsRouteImport.update({
  id: '/market-trends',
  path: '/market-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const JobMatchingRoute = JobMatchingRouteImport.update({
  id: '/job-matching',
  path: '/job-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/job-matching': typeof JobMatchingRoute
  '/market-trends': typeof MarketTrendsRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/skill-gap': typeof SkillGapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/job-matching': typeof JobMatchingRoute
  '/market-trends': typeof MarketTrendsRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/skill-gap': typeof SkillGapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/job-matching': typeof JobMatchingRoute
  '/market-trends': typeof MarketTrendsRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/skill-gap': typeof SkillGapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/job-matching'
    | '/market-trends'
    | '/resume'
    | '/roadmap'
    | '/settings'
    | '/skill-gap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/job-matching'
    | '/market-trends'
    | '/resume'
    | '/roadmap'
    | '/settings'
    | '/skill-gap'
  id:
    | '__root__'
    | '/'
    | '/job-matching'
    | '/market-trends'
    | '/resume'
    | '/roadmap'
    | '/settings'
    | '/skill-gap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobMatchingRoute: typeof JobMatchingRoute
  MarketTrendsRoute: typeof MarketTrendsRoute
  ResumeRoute: typeof ResumeRoute
  RoadmapRoute: typeof RoadmapRoute
  SettingsRoute: typeof SettingsRoute
  SkillGapRoute: typeof SkillGapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skill-gap': {
      id: '/skill-gap'
      path: '/skill-gap'
      fullPath: '/skill-gap'
      preLoaderRoute: typeof SkillGapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-trends': {
      id: '/market-trends'
      path: '/market-trends'
      fullPath: '/market-trends'
      preLoaderRoute: typeof MarketTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-matching': {
      id: '/job-matching'
      path: '/job-matching'
      fullPath: '/job-matching'
      preLoaderRoute: typeof JobMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobMatchingRoute: JobMatchingRoute,
  MarketTrendsRoute: MarketTrendsRoute,
  ResumeRoute: ResumeRoute,
  RoadmapRoute: RoadmapRoute,
  SettingsRoute: SettingsRoute,
  SkillGapRoute: SkillGapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
